Set up non-embedded bin symlinks

diff --git a/package-scripts/angry-omnibus-toolchain/postinst b/package-scripts/angry-omnibus-toolchain/postinst
--- a/package-scripts/angry-omnibus-toolchain/postinst
+++ b/package-scripts/angry-omnibus-toolchain/postinst
@@ -7,7 +7,31 @@
 #   this programming language.  do not touch.
 # - if you are under 40, get peer review from your elders.
 #
+PROGNAME=`basename $0`
 
-echo "youtube.com/watch?v=Xs-tl6GBOBo"
+error_exit()
+{
+  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
+  exit 1
+}
+
+ln -sf /opt/angry-omnibus-toolchain/embedded/bin/git /opt/angry-omnibus-toolchain/bin || error_exit "Cannot link git to /opt/angry-omnibus-toolchain/bin"
+ln -sf /opt/angry-omnibus-toolchain/embedded/bin/ruby /opt/angry-omnibus-toolchain/bin || error_exit "Cannot link ruby to /opt/angry-omnibus-toolchain/bin"
+ln -sf /opt/angry-omnibus-toolchain/embedded/bin/gtar /opt/angry-omnibus-toolchain/bin || error_exit "Cannot link gtar to /opt/angry-omnibus-toolchain/bin"
+ln -sf /opt/angry-omnibus-toolchain/embedded/bin/gtar /opt/angry-omnibus-toolchain/bin/tar || error_exit "Cannot link tar to /opt/angry-omnibus-toolchain/bin"
+ln -sf /opt/angry-omnibus-toolchain/embedded/bin/bash /opt/angry-omnibus-toolchain/bin || error_exit "Cannot link bash to /opt/angry-omnibus-toolchain/bin"
+ln -sf /opt/angry-omnibus-toolchain/embedded/bin/bundle /opt/angry-omnibus-toolchain/bin || error_exit "Cannot link bundle to /opt/angry-omnibus-toolchain/bin"
+ln -sf /opt/angry-omnibus-toolchain/embedded/bin/curl /opt/angry-omnibus-toolchain/bin || error_exit "Cannot link curl to /opt/angry-omnibus-toolchain/bin"
+ln -sf /opt/angry-omnibus-toolchain/embedded/bin/fakeroot /opt/angry-omnibus-toolchain/bin || error_exit "Cannot link fakeroot to /opt/angry-omnibus-toolchain/bin"
+ln -sf /opt/angry-omnibus-toolchain/embedded/bin/gem /opt/angry-omnibus-toolchain/bin || error_exit "Cannot link gem to /opt/angry-omnibus-toolchain/bin"
+ln -sf /opt/angry-omnibus-toolchain/embedded/bin/make /opt/angry-omnibus-toolchain/bin/gmake || error_exit "Cannot link gmake to /opt/angry-omnibus-toolchain/bin"
+ln -sf /opt/angry-omnibus-toolchain/embedded/bin/make /opt/angry-omnibus-toolchain/bin/make || error_exit "Cannot link make to /opt/angry-omnibus-toolchain/bin"
+ln -sf /opt/angry-omnibus-toolchain/embedded/bin/makedepend /opt/angry-omnibus-toolchain/bin || error_exit "Cannot link makedepend to /opt/angry-omnibus-toolchain/bin"
+ln -sf /opt/angry-omnibus-toolchain/embedded/bin/patch /opt/angry-omnibus-toolchain/bin || error_exit "Cannot link patch to /opt/angry-omnibus-toolchain/bin"
+ln -sf /opt/angry-omnibus-toolchain/embedded/bin/pkg-config /opt/angry-omnibus-toolchain/bin || error_exit "Cannot link pkg-config to /opt/angry-omnibus-toolchain/bin"
+ln -sf /opt/angry-omnibus-toolchain/embedded/bin/rake /opt/angry-omnibus-toolchain/bin || error_exit "Cannot link rake to /opt/angry-omnibus-toolchain/bin"
+ln -sf /opt/angry-omnibus-toolchain/embedded/bin/ruby /opt/angry-omnibus-toolchain/bin || error_exit "Cannot link ruby to /opt/angry-omnibus-toolchain/bin"
+
+echo "Thank you for installing the Omnibus Toolchain!"
 
 exit 0
diff --git a/package-scripts/omnibus-toolchain/postinst b/package-scripts/omnibus-toolchain/postinst
--- a/package-scripts/omnibus-toolchain/postinst
+++ b/package-scripts/omnibus-toolchain/postinst
@@ -7,6 +7,30 @@
 #   this programming language.  do not touch.
 # - if you are under 40, get peer review from your elders.
 #
+PROGNAME=`basename $0`
+
+error_exit()
+{
+  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
+  exit 1
+}
+
+ln -sf /opt/omnibus-toolchain/embedded/bin/git /opt/omnibus-toolchain/bin || error_exit "Cannot link git to /opt/omnibus-toolchain/bin"
+ln -sf /opt/omnibus-toolchain/embedded/bin/ruby /opt/omnibus-toolchain/bin || error_exit "Cannot link ruby to /opt/omnibus-toolchain/bin"
+ln -sf /opt/omnibus-toolchain/embedded/bin/gtar /opt/omnibus-toolchain/bin || error_exit "Cannot link gtar to /opt/omnibus-toolchain/bin"
+ln -sf /opt/omnibus-toolchain/embedded/bin/gtar /opt/omnibus-toolchain/bin/tar || error_exit "Cannot link tar to /opt/omnibus-toolchain/bin"
+ln -sf /opt/omnibus-toolchain/embedded/bin/bash /opt/omnibus-toolchain/bin || error_exit "Cannot link bash to /opt/omnibus-toolchain/bin"
+ln -sf /opt/omnibus-toolchain/embedded/bin/bundle /opt/omnibus-toolchain/bin || error_exit "Cannot link bundle to /opt/omnibus-toolchain/bin"
+ln -sf /opt/omnibus-toolchain/embedded/bin/curl /opt/omnibus-toolchain/bin || error_exit "Cannot link curl to /opt/omnibus-toolchain/bin"
+ln -sf /opt/omnibus-toolchain/embedded/bin/fakeroot /opt/omnibus-toolchain/bin || error_exit "Cannot link fakeroot to /opt/omnibus-toolchain/bin"
+ln -sf /opt/omnibus-toolchain/embedded/bin/gem /opt/omnibus-toolchain/bin || error_exit "Cannot link gem to /opt/omnibus-toolchain/bin"
+ln -sf /opt/omnibus-toolchain/embedded/bin/make /opt/omnibus-toolchain/bin/gmake || error_exit "Cannot link gmake to /opt/omnibus-toolchain/bin"
+ln -sf /opt/omnibus-toolchain/embedded/bin/make /opt/omnibus-toolchain/bin/make || error_exit "Cannot link make to /opt/omnibus-toolchain/bin"
+ln -sf /opt/omnibus-toolchain/embedded/bin/makedepend /opt/omnibus-toolchain/bin || error_exit "Cannot link makedepend to /opt/omnibus-toolchain/bin"
+ln -sf /opt/omnibus-toolchain/embedded/bin/patch /opt/omnibus-toolchain/bin || error_exit "Cannot link patch to /opt/omnibus-toolchain/bin"
+ln -sf /opt/omnibus-toolchain/embedded/bin/pkg-config /opt/omnibus-toolchain/bin || error_exit "Cannot link pkg-config to /opt/omnibus-toolchain/bin"
+ln -sf /opt/omnibus-toolchain/embedded/bin/rake /opt/omnibus-toolchain/bin || error_exit "Cannot link rake to /opt/omnibus-toolchain/bin"
+ln -sf /opt/omnibus-toolchain/embedded/bin/ruby /opt/omnibus-toolchain/bin || error_exit "Cannot link ruby to /opt/omnibus-toolchain/bin"
 
 echo "Thank you for installing the Omnibus Toolchain!"
 
